# Site settings
title: Blog
email: rj222gp@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  A description about my site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  JohanssonRickard

# Build settings
markdown: kramdown
